inherit_from: .rubocop_todo.yml

require:
  - rubocop-faker
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/RaiseException:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'app/channels/graphql_channel.rb'
    - 'app/controllers/graphql_controller.rb'

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/LambdaCall:
  EnforcedStyle: braces

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
