version: "3.7"

services:

  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tv
      POSTGRES_PASSWORD: tv
      POSTGRES_DB: tv_development
    restart: always

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

volumes:
  db-data:
  redis-data:

networks:
  default:
    name: tv
