# frozen_string_literal: true

user = User.create!(name: "anonymous")
playlist = Playlist.create!(name: "Your playlist", user: user)
playlist = Playlist.create!(name: "Playlist 1", user: user)
playlist = Playlist.create!(name: "Playlist 2", user: user)
playlist = Playlist.create!(name: "Playlist 3", user: user)
playlist = Playlist.create!(name: "Playlist 4", user: user)
playlist = Playlist.create!(name: "Playlist 5", user: user)
playlist = Playlist.create!(name: "Playlist 6", user: user)
playlist = Playlist.create!(name: "Playlist 7", user: user)
playlist = Playlist.create!(name: "Playlist 8", user: user)
playlist = Playlist.create!(name: "Playlist 9", user: user)
playlist = Playlist.create!(name: "Playlist 10", user: user)
playlist = Playlist.create!(name: "Playlist 11", user: user)
playlist = Playlist.create!(name: "Playlist 12", user: user)
playlist = Playlist.create!(name: "Playlist 14", user: user)
playlist = Playlist.create!(name: "Playlist 15", user: user)
playlist = Playlist.create!(name: "Playlist 16", user: user)
playlist = Playlist.create!(name: "Playlist 17", user: user)
